In [6]:
import pandas as pd
c={1:'Country', 3:'Energy Supply', 4:'Energy Supply per Capita', 5:'% Renewable'}
fl=pd.read_excel("Energy Indicators.xls",header=None,footer=None)
d=pd.DataFrame(fl)
d.drop([0,2],axis=1,inplace=True)
d.drop(d.index[245:],inplace=True)
d.drop(d.index[:18],inplace=True)
d.rename(columns=c,inplace=True)
d.reset_index(inplace=True)
d.drop('index',axis=1,inplace=True)
f2=pd.read_csv('World.csv',header=None)
d2=pd.DataFrame(f2)
d2.drop(d2.index[:4],inplace=True)
d2.reset_index(inplace=True)
d2.drop('index',axis=1,inplace=True)
d2.columns=d2.iloc[0]
d2.drop(d2.index[0],inplace=True)
s1=pd.merge(d,d2,how='inner',on=['Country'])
#s1
#d2
d

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,321,10,78.6693
1,Albania,102,35,100
2,Algeria,1959,51,0.55101
3,American Samoa,...,...,0.641026
4,Andorra,9,121,88.6957
5,Angola,642,27,70.9091
6,Anguilla,2,136,0
7,Antigua and Barbuda,8,84,0
8,Argentina,3378,79,24.0645
9,Armenia,143,48,28.2361
10,Aruba,12,120,14.8707
11,Australia,5386,231,11.8108
12,Austria,1391,164,72.4528
13,Azerbaijan,567,60,6.38434
14,Bahamas,45,118,0
15,Bahrain,574,425,0
16,Bangladesh,1625,10,1.96633
17,Barbados,19,69,0
18,Belarus,1142,120,0.463389
19,Belgium,2338,210,9.95974
20,Belize,13,39,64.69
21,Benin,170,16,0
22,Bermuda,6,88,0
23,Bhutan,63,83,100
24,Bolivia (Plurinational State of),336,32,31.4771
25,"Bonaire, Sint Eustatius and Saba",5,213,0
26,Bosnia and Herzegovina,266,70,41.4647
27,Botswana,86,39,0.131406
28,Brazil,12149,59,69.648
29,British Virgin Islands,2,85,0
...,...,...,...,...
197,Switzerland,1113,136,57.7455
198,Syrian Arab Republic,542,28,11.5683
199,Tajikistan,106,13,99.7429
200,Thailand,5336,79,4.30519
201,The former Yugoslav Republic of Macedonia,117,56,26.1405
202,Timor-Leste,7,6,0
203,Togo,134,19,80.1802
204,Tonga,3,28,0
205,Trinidad and Tobago,824,611,0
206,Tunisia,430,39,3.49255
207,Turkey,4897,64,28.5367
208,Turkmenistan,1102,210,0
209,Turks and Caicos Islands,3,85,0
210,Tuvalu,...,...,0
211,Uganda,452,12,68.0182
212,Ukraine,4844,107,8.06731
213,United Arab Emirates,2710,300,0
214,United Kingdom of Great Britain and Northern I...,7920,124,10.6005
215,United Republic of Tanzania,994,20,31.0728
216,United States of America,90838,286,11.571
217,United States Virgin Islands,...,...,0
218,Uruguay,196,58,71.605
219,Uzbekistan,1798,62,21.3284
220,Vanuatu,3,10,14.7059
221,Venezuela (Bolivarian Republic of),2871,95,67.8345
222,Viet Nam,2554,28,45.3215
223,Wallis and Futuna Islands,0,26,0
224,Yemen,344,13,0
225,Zambia,400,26,99.7147
226,Zimbabwe,480,32,52.5361